name: Build and Release Quaternary
on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'
      - '!v*-alpha*'
  workflow_dispatch:
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs: 
      semVer: ${{ steps.gitversion.outputs.semver }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
  export-game:
    name: Export Game
    runs-on: ubuntu-latest
    needs: calculate-version
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.1
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./src
          archive_output: true
      - name: create-release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ needs.calculate-version.outputs.semVer }}
          commit: ${{ github.sha }}
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
          artifactErrorsFailBuild: true
          prerelease: true
          generateReleaseNotes: true
